services:
  - type: pserv
    name: kingdom-77-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: BOT_OWNER_ID
        sync: false
    autoDeploy: true
