services:
  - type: web
    name: kingdom-77-bot
    runtime: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: BOT_OWNER_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
