services:
  - type: web
    name: kingdom-77-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
